#Package or vulnerability scanning workflow for the two-tier-app repository
#pip audit is a built-in tool that checks for vulnerabilities in Python dependencies. It compares the installed packages against a database of known vulnerabilities and provides a report of any issues found. This workflow will run pip audit on the codebase to identify any security vulnerabilities in the dependencies.

name: Dependency Scan Workflow

on: 
    workflow_call:

jobs:
    dependency-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: pip install -r requirements.txt
                  
            - name: Audit Dependency
              run: pip audit

