
name: DevsecOps Workflow

on:   
    workflow_dispatch:

jobs:
  Code-Quality:
    uses: ./.github/workflows/code-quality.yml

  secrets-scan:
    uses: ./.github/workflows/secrets-scan.yml
                        
  dockerlint:
    uses: ./.github/workflows/dockerlint.yml

  image-scan:
    needs: [dockerlint]
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit 
  
  docker-build-push:
    needs:  [secrets-scan, image-scan]
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit
    
  docker-deploy:
    needs: docker-build-push
    uses: ./.github/workflows/docker-to-server.yml 
    secrets: inherit