
name: DevsecOps Workflow

on:   
    workflow_dispatch:

jobs:

        call-workflow:
            uses: mahak933/two-tier-app/.github/workflows/code-quality.yml@project
            
        Code-Quality:
            uses: mahak933/two-tier-app/.github/workflows/code-quality.yml@project

        secrets-scan:
            uses: mahak933/two-tier-app/.github/workflows/secrets-scan.yml@project
            
        dependency-scan:
            uses: mahak933/two-tier-app/.github/workflows/dependency-scan.yml@project
            
        dockfilelint:
            uses: mahak933/two-tier-app/.github/workflows/dockfilelint.yml@project

            