
name: DevsecOps Workflow

on:   
    push:
        branches: [main]

jobs:
    
  Code-Quality:
    uses: ./.github/workflows/code-quality.yml

  secrets-scan:
    uses: ./.github/workflows/secrets-scan.yml
                 
  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml

  dockerlint:
    uses: ./.github/workflows/dockerlint.yml

  docker-build-push:
    needs:  [Code-Quality, secrets-scan, dependency-scan, dockerlint]
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit

  image-scan:
    needs: [docker-build-push]
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit 
  
  docker-deploy:
    needs: [image-scan, docker-build-push]
    uses: ./.github/workflows/docker-to-server.yml 
    secrets: inherit