# This workflow will run a secrets scan on the codebase using a tool like GitLeaks.

name: secrets scan workflow

on:
    workflow_call:

jobs:
    secrets-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run GitLeaks for secrets scanning
              uses: gitleaks/gitleaks-action@v2
              env:
                GITLEAKS_TOKEN: ${{ secrets.GITLEAKS_TOKEN }} 